### ISSUE TITLE
No default gateway set by bosh-agent

### ISSUE THREAD

**Issue by f-guichard** [cloudfoundry-community/bosh-cloudstack-cpi-release#21]
After deploying a new VM with bosh, stemcell 3173, the current routing table is implemented : 

```
vcap@34f6aed0-3170-467b-a1c3-98a254366bdb:~$ sudo su
[sudo] password for vcap:
root@34f6aed0-3170-467b-a1c3-98a254366bdb:/home/vcap# ip route s
10.234.254.0/24 dev eth0  proto kernel  scope link  src 10.234.254.61
```

No default gateway is set.

When looking down into /etc/network/interfaces, here's what is set by bosh-agent :

```
root@34f6aed0-3170-467b-a1c3-98a254366bdb:/home/vcap# cat /etc/network/interfaces
# Generated by bosh-agent
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 10.234.254.61
    network 10.234.254.0
    netmask 255.255.255.0

dns-nameservers 10.234.50.180 10.234.71.124 10.234.254.200
```

**Comment by poblin-orange** [comment]
The use case u meet is when the target vm is not on the same network as the bosh director.

Unfortunatly the default [gateway,dns]  is not set in cpi provided settings.json. This might explain why the default route is not set by bosh-agent.

As a workaround, i suggest you switch the use_dhcp flag of your bosh director / cpi to true.
You should get the expected "manuel IP" through cloudstack dhcp server, plus correct route configuration
see http://bosh.io/jobs/cloudstack_cpi?source=github.com/cloudfoundry-community/bosh-cloudstack-cpi-release&version=8#p=cpi.use_dhcp

**Comment by poblin-orange** [comment]
v10 generates network config for bosh-agent in settings.json (default:[dns,gateway]).
Gives the following result on dev platform, with cpi use_dhcp=false

/var/vcap/bosh/settings.yml

```
"agent_id":"71f717d6-3c50-41f8-aeb3-d52a71d159f1","blobstore":{"provider":"dav","options":{"blobstore_path":"/var/vcap/micro_bosh/data/cache","endpoint":"http://10.234.228.153:25251","password":"ZZZZ","user":"agent"}},"disks":{"system":"/dev/xvda","ephemeral":"/dev/sdb","persistent":{},"raw_ephemeral":null},"env":{"bosh":{"password":"","keep_root_password":false}},"networks":{"cf1":{"type":"manual","ip":"10.234.242.47","netmask":"255.255.255.0","gateway":"10.234.242.1","resolved":false,"use_dhcp":false,**"default":["dns","gateway","gateway","dns"]**,"dns":["10.234.50.180","10.234.71.124","10.234.228.153"],"mac":"06:55:c6:00:00:79","preconfigured":false}},"ntp":[],"mbus":"nats://nats:gikzaidean@10.234.228.153:4222","vm":{"name":"cpivm-628074e1-e6bf-4c22-810a-d89246eccf80"},"trusted_certs":""}
```

=> network is set with default":["dns","gateway","gateway","dns"]

/etc/network/interfaces

```
# Generated by bosh-agent
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address 10.234.242.47
    network 10.234.242.0
    netmask 255.255.255.0
    broadcast 10.234.242.255
    gateway 10.234.242.1
```

=> ip is static

routes

```
root@71f717d6-3c50-41f8-aeb3-d52a71d159f1:/etc/network# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.234.242.1    0.0.0.0         UG    0      0        0 eth0
10.234.242.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

=> default route is set

**Comment by poblin-orange** [comment]
fixed in v10

**Comment by mjsjinsu** [comment]
with this issue
I used to dhcp options in application.yml
I try to change dhcp -> manaul network configuration
It's good fixed point

**Comment by poblin-orange** [comment]
@mjsjinsu glad it helped :-)
Dont hesitate to open issue if you meet other problems with the cpi
