### ISSUE TITLE
Adding an api throttling property to limit the number of url calls per second

### ISSUE THREAD

**Issue by f-guichard** [cloudfoundry-community/bosh-cloudstack-cpi-release#23]
Hello,

  we need to let a property in the cpi_property "cs_max_api_call" to limit the number of call send by the cpi cs driver to the cloudstack manager, which should be 20 per default.

**Comment by poblin-orange** [comment]
Many cpi to cloudstack api call are async task result polls.
Which type of apI call do you want to throttle? create_vm and or create_disk?
Maybe u  can start by throttling at bosh director level (number of worker thread)

**Comment by poblin-orange** [comment]
bosh director has already mechanism to limit iaas actions limitations. We usually set a lower value to max_threads parameter.

http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=234#p=director.max_threads

I guess cloudstack has also some api throttling mechanism.
Given these 2 options, i do not think the cpi is the good place for throttling

**Comment by poblin-orange** [comment]
hystrix instrumentation has been added. First version limits the concurrent cpi verb to 10 (ie: max 10 concurrent cpi.create_vm, max 10 concurrent cpi.create_disk).
This built in cpi mechanism can protect the iaas in case of bosh max_thread unadapted configuration
