### ISSUE TITLE
Need to set requireshvm property to true in registerTemplate call

### ISSUE THREAD

**Issue by f-guichard** [cloudfoundry-community/bosh-cloudstack-cpi-release#25]
To benefit from PVHVM improvements in performance, it's required to set requireshvm key to value true in a native call api (Jclouds 1.9.3 doesn't seem to support this property from what we tested up to now).

See : http://cloudstack.apache.org/docs/api/apidocs-4.7/root_admin/registerTemplate.html

**Comment by poblin-orange** [comment]
option is available in jclouds
https://github.com/apache/jclouds/blame/master/apis/cloudstack/src/main/java/org/jclouds/cloudstack/options/RegisterTemplateOptions.java#L133
need more context to place the property. Is it bosh director level property or should it be deduced from stemcell  manifest, to cover all users use cases?

**Comment by poblin-orange** [comment]
http://wiki.xenproject.org/wiki/Understanding_the_Virtualization_Spectrum#The_Paravirtualization_Spectrum
will enable better io perf on xen 6.5
as its related to xen version, and has potential impact, need to set it in cpi property (default: false)

**Comment by poblin-orange** [comment]
fixed with new property stemcell_requires_hvm
tested with stemcell_requires_hvm true on ikoula
