### ISSUE TITLE
cloudstack stemcell root size volume

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/bosh-cloudstack-cpi-release#26]
Hi there
I have a question about stemcell root volume size
I deployed CloudFoundry with cloudstack-cpi release based on cloudstack/xen
and used ubuntu stemcell 3192

I wonder if i resize root volume size
Unlike kvm based IaaS, cloudstack/xen base is didn't support flexible root volume size  

I think root partition size 3GB is too small 
It could be problem in the managing VM with bosh
I worried about root partition will be full
Also i know that, Most of job use attached data volume (ephemeral_disk and persisent disk)

I didn't know about stemcell bulid process and any infomation
Can you give me Opinion?

root@d4647dc0-ff65-48f5-9e2a-83c792f049a8:~# df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  3.9G  4.0K  3.9G   1% /dev
tmpfs          tmpfs     802M  200K  802M   1% /run
**/dev/xvda1     ext4      2.9G  1.2G  1.7G  42% /**
none           tmpfs     4.0K     0  4.0K   0% /sys/fs/cgroup
none           tmpfs     5.0M     0  5.0M   0% /run/lock
none           tmpfs     4.0G     0  4.0G   0% /run/shm
none           tmpfs     100M     0  100M   0% /run/user
/dev/xvdb2     ext4      190G  2.0G  178G   2% /var/vcap/data
tmpfs          tmpfs     1.0M   36K  988K   4% /var/vcap/data/sys/run
/dev/loop0     ext4      120M  1.6M  115M   2% /tmp

**Comment by poblin-orange** [comment]
Hello @mjsjinsu 
i think the root fs size should be ok.
As u know, all bosh releases uses ephemeral disk ( /var/vcap/data) for logs and temp files.
Globally, only base os packages and swap file are set on root disk.

I even have feedbacks from user considering 3Go to be to big for a template :-)

So you should not meet any issue. If u need more temp, just set a bigger ephemeral disk size
Dont hesitate to tell me if u meet a root fs file full, on a given bosh release
