### ISSUE TITLE
vm conflict ip check is not compatible with Cloudstack based VPC

### ISSUE THREAD

**Issue by f-guichard** [cloudfoundry-community/bosh-cloudstack-cpi-release#30]
Hi,

  in a typical vpc deployment, tenants are isolated using layer-2-like mechanisims (802.1Q, 802.1ah, vxlan for instances).

bosh needs to understand that the same ip adress can be used multiple times in the same network zone (for instance, cloudstack zone) in an advanced network topology.

To prevent bosh from being confused with ip overlap, a new property should be set to specify if ip adress are to be checked at network level or zone level.

This issue is aimed to adress specific use cases, such as providing multiple CFYs sharing the same network configurations but in differant tenants of the same Virtual Private Cloud

**Comment by poblin-orange** [comment]
to clarify, bosh director has no issue with ip conflict between deployment.
This issue seem to be related to the ip check in the cpi. Convenient as it can identify ip conflict with zombie vm in a cloudstack zone. This control might be uncompatible with a cloudstack VPC configuration
Can u provide the error message your getting?

**Comment by dpassante** [comment]
You're right, the error message is sent by the IP-check done at the zone level in the CPI.

> Error 100: java.lang.IllegalArgumentException: The required IP 192.168.6.17 is not available: used by vm cpivm-c7f87758-79bb-40d2-a8a6-c562b9e9756c.

It appears when an account tries to use the same ip address in multiples deployments, even if instances are provisioned on different VLAN.
This should affect any deployment done on ACS isolated network.

**Comment by poblin-orange** [comment]
A probable workaround to this issue is to use per VPC bosh account (so each cpi can only see the VPC network it manages) ?

**Comment by poblin-orange** [comment]
Fixed by searching conflicting vms only on the create_vm target network (so no conflict if same ip use on another network)

**Comment by poblin-orange** [comment]
delivered in v16
