### ISSUE TITLE
Check  Bosh registry URI configuration consistency

### ISSUE THREAD

**Issue by f-guichard** [cloudfoundry-community/bosh-cloudstack-cpi-release#37]
All first bosh deployments has failed since bosh registry Basic Auth has been implemented, because of wrong endpoint specification in yaml file.

URI should be built from endpoint + user + password from bosh yaml deployment file.

**Comment by poblin-orange** [comment]
basic-auth was added in cpi v11.
The change was clearly stated in the release note https://github.com/cloudfoundry-community/bosh-cloudstack-cpi-release/releases/tag/v11, in the "uncompatible change" section, with a manifest snippet. Hard to be more explicit ;-)

Agreed thats a bit redundant. However, this is the same on other CPI (openstack, vcloud, aws). 

This redudancy enables use cases like AWS bosh-init through ssh tunnel, where bosh-registry is accessed with a http://127.0.0.1 address by the bosh agent.

Not sure there is enough value to diverge from the other CPIs

**Comment by poblin-orange** [comment]
finally, a simple consistency check should match the requirement see PR https://github.com/cloudfoundry-community/bosh-cloudstack-cpi-core/pull/5
