### ISSUE TITLE
CPI does not support bosh cpi v2 and will break when the registry is removed

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry-community/bosh-cloudstack-cpi-release#59]
The bosh registry has been deprecated for a couple of years and we're starting work on removing it from the bosh director.

This cpi currently only supports cpi v1 and still requires the registry.

The differences between v1 and v2 are not super large and can be found here: https://bosh.io/docs/v2-migration-guide/

**Comment by jpalermo** [comment]
CC: @romain-dartigues & @ArthurHlt as you recently added the cloudstack cpi to bosh-deployment

**Comment by jpalermo** [comment]
Sorry, didn't realize there was a replacement cpi and this one is no longer used. (hopefully)

**Comment by romain-dartigues** [comment]
@jpalermo < you are right, it is confusing and might be nice to re-open this issue to address the fact this repository is now deprecated, what is next and archive it.

@poblin-orange, @gberche-orange?

**Comment by rkoster** [comment]
Maybe add a notice with a link to the new cpi at the top of the readme and then archive the repo?

**Comment by gberche-orange** [comment]
thanks @rkoster @romain-dartigues  @jpalermo for the head up.  Both https://github.com/cloudfoundry-community/bosh-cloudstack-cpi-release/ and https://github.com/orange-cloudfoundry/bosh-cloudstack-cpi-release are now archived.
